### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by pkerpedjiev** [patorjk/d3-context-menu#10]
Is there a way to import d3-context-menu using es6 import statements?

**Comment by patorjk** [comment]
I'm not sure, I haven't really done much with ES6 yet.

**Comment by pkerpedjiev** [comment]
No problem, I just took out the contextMenu function, placed it in its own file and added an 'export' in front of it. Seems to work :)

**Comment by patorjk** [comment]
Interesting, I'll have to dig into how to make it more compatible with ES6 import. Glad you got it to work though.
