### ISSUE TITLE
multiple menu items

### ISSUE THREAD

**Issue by LexCog** [patorjk/d3-context-menu#13]
I'm having trouble getting this to work with more than one menu item.  With multiple items the default right-click menu appears.

(I'm running it on a Macbook Pro, Yosemite, and Chrome.)

Any thoughts?

Thanks.

**Comment by patorjk** [comment]
Does the example in the examples folder work?

**Comment by LexCog** [comment]
Thanks for getting back to me so quickly.

Yes, the example does work.  And importing all the relevant parts into my setup made that work as well.  On investigation, it turned out that I had been using an older version of d3-context-menu.js!?  Sorry about that.  The issue can be closed.

Thanks for this tool, and, again, thanks for getting back to me so quickly.

Best,

LC

**Comment by patorjk** [comment]
No problem, glad I could help.
