### ISSUE TITLE
Add Id attribute for menu item

### ISSUE THREAD

**Issue by SivaJonnala** [patorjk/d3-context-menu#14]
I want to add an Id attribute for the menu item.
Is there any way to add Id to the menu item respected " li " Item"

**Comment by Frazer** [comment]
noramlly  github Issues aren't the place to ask questions like this. Its better that you attempt something, and if you cant make it work, then ask on StackOverflow :) 

But this question is in the README

https://github.com/patorjk/d3-context-menu#context-sensitive-menu-items

hope that is enough for you to work it out :)

**Comment by adrianbota** [comment]
@SivaJonnala No way to add an `id` for the `<li>` element, however you can add your own html in the `title`:

```
{
    title: '<div id="foo">Item 1</div>'
}
```

and it will render like

`<li><div id="foo">Item 1</div></li>`
