### ISSUE TITLE
How to add an image to the context-menu?

### ISSUE THREAD

**Issue by n0gare** [patorjk/d3-context-menu#18]
Hello guys,

I want to add an image to some titles of the context-menu, but I dont know how
Can anyone help me?

I tried something like this:

var menu = [
    {title: 'MyItem',
     icon: 'C:...\Desktop\Pics\f.png',
     action: function (elm, d, i) {...}
    },

I hope you can help me.

Best regards!

**Comment by Frazer** [comment]
github Issues aren't the place to ask questions like this. Its better that you attempt something, and if you cant make it work, then ask on StackOverflow :) Happy Hacking

**Comment by adrianbota** [comment]
@n0gare `title` supports html tags, so try including an `<img ...>` there. Make sure to sanitise the html you're putting in the `title`
