### ISSUE TITLE
In fullscreen mode, context menu won't show up in certain browsers

### ISSUE THREAD

**Issue by tpham** [patorjk/d3-context-menu#19]
If context menu element is not contained within the DOM element used for full screen mode, certain browsers (such as Firefox) just won't show it. Perhaps, d3-context-menu could be enhanced to allow the specification of a selector (as an option) so that the context menu be inserted in that container instead.

**Comment by Frazer** [comment]
could you attempt to do this yourself on your own fork?  I may need it later this year :)

**Comment by adrianbota** [comment]
Currently this is a convenient way to detect when user clicks outside of the menu, and, when that happens, close the menu. Could you put together an example where we can see this issue?

**Comment by adrianbota** [comment]
Closing for now, please reopen/open another ticket if this is still an issue. Thanks!
