### ISSUE TITLE
can it append image for d3-context-menu

### ISSUE THREAD

**Issue by zmmail** [patorjk/d3-context-menu#2]
d3-context-menu have supported menu title by word. I think it will be more user-friendly if it can append image( png or svg ). Thanks!

**Comment by patorjk** [comment]
This is a good idea, I'll think about this. Though I'm open to ideas or pull requests.

**Comment by fr0z3nfyr** [comment]
Didn't get the point exactly!! I tried using an image tag inside `title:'<img src="some path">'` and it worked absolutely fine. I even tried bootstrap glyphicons and they worked too...
