### ISSUE TITLE
bower install doesn't work

### ISSUE THREAD

**Issue by dqueffeulouatw** [patorjk/d3-context-menu#23]
Hi, 

when I make a bower install I have the following error:
bower d3-context-menu#0.1.1     ENORESTARGET No version found that was able to satisfy 0.1.1

Same with:
bower install d3-context-menu

Maybe it's a version problem because bower.json contains 0.1.1 and npm contains 0.1.2.

**Comment by patorjk** [comment]
I meant to test this last night but it slipped my mind. Right now I'm not on a computer where I can't test bower, but I believe you're correct about the version number. I've updated the incorrect version number and will test it tonight. Thank you for letting me know.
