### ISSUE TITLE
How to use it with d3 v4

### ISSUE THREAD

**Issue by dagrende** [patorjk/d3-context-menu#27]

**Comment by dagrende** [comment]
I found an answer that works in my project with node, webpack, es6 etc.

1. install d3-context-menu with `npm install d3-context-menu --save`
1. copy the css from css/d3-context-menu.css into your css
1. import d3-context-menu with `import contextMenuFactory from 'd3-context-menu';`
1. create the context menu handler with `let contextMenu = contextMenuFactory(d3);`
1. use context menu in event handler like `aSelection.on('contextmenu', contextMenu(menu));`

See example code in https://github.com/FindOut/d3-directed-graph.

**Comment by sudhakar-sekar** [comment]
I am trying the above steps in d3v4 and angular2(typescript).
It's not working, right click in UI nothing will show, it shown as empty?
can you please help me out this ASAP.....

**Comment by roypardi** [comment]
I don't know the "right" way to do it – but in my non-es6, d3 Electron project I got it working by:

1. putting the *d3-context-menu.js* file in my js directory and referencing it from the main index.html along with the associated css file:
```
<script type="text/javascript" src="js/d3-context-menu.js"></script>
<link href="css/d3-context-menu.css" type="text/css" rel="stylesheet" />
```
2. in my main script I initialize *d3-context-menu.js* like this:
```
let d3contextMenuLib = require('./js/d3-context-menu')
let d3ContextMenu = d3contextMenuLib(d3);
```
3. finally, I attach the event listeners to the objects that should get them (I don't need the "onOpen"/"onClose " functions shown in the example code.
```
.on('contextmenu', d3ContextMenu(eventMenu)); 
```

**Comment by adrianbota** [comment]
thanks all for providing your solutions
