### ISSUE TITLE
div gets appended outside body tag instead of in it

### ISSUE THREAD

**Issue by SaloniDesai** [patorjk/d3-context-menu#30]
I am trying to implement a list on right click of a data node. d3-context-menu plugin is perfect for my requirements. But when I tried to use it in my code, the library is not working. When i right click on the data node, it won't give me a menu and instead an extra scroll bar gets added to the page. When I tried to debug the behavior I noticed that the div element with class "d3-context-menu" is outside the body tag. I feel that could be the reason of list not appearing. The plugin is working on the background and is not visible.

I followed this example : [http://plnkr.co/edit/hAx36JQhb0RsvVn7TomS?p=preview]
My code looks like this:
```
eventGroup = focusClip.selectAll(".event").data(data);
eventGroupEnter = eventGroup.enter().append("svg");
// Event Group
            eventGroup
                .attr("class", "event")
                .attr("x", function (d) { return parseInt(x(d.time)) - 10; }) // offset for the bg and center of dot
                .attr("y", function (d) { return parseInt(y(d.plotY)); })
                .attr("width", function (d) { return parseInt((d.label.length / 2)) + 60 + "em";})
                .attr("height", "20");

            // Background
            eventGroup.select("rect")
                .attr("x", 0) // removes the "<rect> attribute x: Expected length, 'NaN'" Error
                .attr("y", 4)
                .attr("width", "100%")
                .attr("height", "12")
                .attr("fill", "url(#event-bg)");

            menu = [{
                title: "Item #1"
            }];
            // Dot
            eventGroup.select("circle")
                .attr("class", "dot")
                .attr("r", 4)
                .attr("cx", 10)
                .attr("cy", 10)
                .attr("fill", function(d) { return d.evtColor ? d.evtColor : "#229ae5"; })
                .attr("stroke", function(d) { return d.evtColor ? d.evtColor : "#229ae5"; })
                .attr("stroke-width", 2)
                .on("contextmenu", d3.contextMenu(menu, function() {
                    console.log("Quick! Before the menu appears!");
                }))
                .on("mouseenter", tooltip.mouseover)
                .on("mouseleave", tooltip.mouseout)
                .on("click", annotateBox.click);
```
I am trying to get the list on the dot element. So when i right click on the dot, the menu should appear. Currently, when I right click on the dot, an extra scroll bar appears and even the console message is displayed but the list is not visible.

**Comment by adrianbota** [comment]
@SaloniDesai I suggest using stackoverflow to try and debug this issue. It is clearly an integration issue, perhaps an incompatibility with your app.
