### ISSUE TITLE
Incompatibility with d3 v4

### ISSUE THREAD

**Issue by kaidjohnson** [patorjk/d3-context-menu#38]
Using the following code for bootstrapping the contextMenu, with d3 v4, webpack v4, and babel v7:

```
import * as d3 from 'd3';
import contextMenu from 'd3-context-menu';
d3.contextMenu = contextMenu(d3);
```

I'm receiving the following error:

```
Uncaught TypeError: Cannot read property 'pageX' of null
    at Object.contextMenu (d3-context-menu.js:170)
```

Peeking into the code:

```
				// display context menu
				d3.select('.d3-context-menu')
					.style('left', (position ? position.left : d3.event.pageX - 2) + 'px')
					.style('top', (position ? position.top : d3.event.pageY - 2) + 'px')
					.style('display', 'block');
```

In v4, `d3.event` is null until an actual event is defined, thus the error. I'm expecting a simple guard to check to ensure `d3.event` will suffice to get things working with v4.

Thanks in advance!

**Comment by patorjk** [comment]
Sorry for the delayed response. You don't want to call contextMenu(d3) until a contextmenu event has fired. That function is what displays the menu. Once you've done that, it should work fine with version 4 (just tried to out myself to be sure).

**Comment by AliAmjad** [comment]
Could you please share resolution as I'm also getting this error in my Angular 6 app.

**Comment by nguyenlamlll** [comment]
As a beginner, I would definitely be waiting for a hint as well :(
