### ISSUE TITLE
D3 6.0 compatibility

### ISSUE THREAD

**Issue by ngg** [patorjk/d3-context-menu#55]
D3 6.0 changed event handling logics (see [D3 6.0 migration guide](https://observablehq.com/d/f91cccf0cad5e9cb#events)), will you consider upgrading?

**Comment by patorjk** [comment]
I'd accept a PR.

**Comment by andreasmueller92** [comment]
@patorjk any news on the issue? The PR #57 by @ngg has been open for quite some time now. PR works like a charm on my end.

**Comment by patorjk** [comment]
I missed that sorry, I'll try it out tonight.

**Comment by patorjk** [comment]
Just published an update, library should now work with D3 6.
