### ISSUE TITLE
Injecting html in the item titles ?

### ISSUE THREAD

**Issue by AlexisPister** [patorjk/d3-context-menu#61]
Is it possible to have more control in the title of a menu item, to inject html ? For example, I would like to add svg shapes to each of the items before their title.

Thanks

**Comment by patorjk** [comment]
Does using HTML in the title not work? It's been a while since I've used this project, but cursory look (https://github.com/patorjk/d3-context-menu/blob/master/js/d3-context-menu.js#L227) makes me think that might work. If not, I'd be open to a PR to support this.

**Comment by AlexisPister** [comment]
Actually it's working sorry for the post
