### ISSUE TITLE
Add support for close callback

### ISSUE THREAD

**Issue by jontayesp** [patorjk/d3-context-menu#8]
It would be useful to have an optional closeCallback so I can reclass nodes that are no longer selected. The closeCallback would be called when the menu is dismissed or when an action is clicked.

**Comment by patorjk** [comment]
I haven't had a chance to add this in, but I like this idea. My thought process right now is that the syntax would look something like this:

    .on('contextmenu', d3.contextMenu(menu, {
        onOpen: function() { console.log('Quick! Before the menu appears!');}
        onClose: function() { console.log('Menu is now no longer visible.');}
    }));

This would allow the current syntax of just taking in a function to default to being the onOpen call.

**Comment by jontayesp** [comment]
That would be awesome. Thanks!

**Comment by patorjk** [comment]
No problem, code has been updated.
